<?php // Include the main TCPDF library (search for installation path).
require_once('vendor/TCPDF-main/tcpdf.php');
session_start();
include "db.php";

 $name=$_SESSION['name'];
 $cdate=date('Y-m-d');
 if($_GET['cid']){
     $cid=$_GET['cid'];
 }
 else{

  $cid='all';
 }
//Fetch Customers Data from DB
if($cid==='all'){
    $sql = mysqli_query($conn, "SELECT   * FROM customers  "); 
    $result=mysqli_fetch_all($sql,MYSQLI_ASSOC);
    $sql2 = mysqli_query($conn, "SELECT   * FROM customer_borrow "); 
    $result2=mysqli_fetch_all($sql2,MYSQLI_ASSOC);
    $sql3 = mysqli_query($conn, "SELECT   * FROM borrow_payment "); 
    $result3=mysqli_fetch_all($sql3,MYSQLI_ASSOC);
}
  else{
      $sql = mysqli_query($conn, "SELECT   * FROM customers where id='$cid' "); 
    $result=mysqli_fetch_assoc($sql);
    $sql2 = mysqli_query($conn, "SELECT   * FROM customer_borrow where cid='$cid' "); 
    $result2=mysqli_fetch_all($sql2,MYSQLI_ASSOC);
    $sql3 = mysqli_query($conn, "SELECT   * FROM borrow_payment  where cid='$cid'"); 
    $result3=mysqli_fetch_all($sql3,MYSQLI_ASSOC);
  }

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($name);
$pdf->SetTitle('Borrow Customers Report');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
$head="Generated By: ". $name ."\r\n Date: ".$cdate;
// set default header data
$pdf->SetHeaderData("NO", PDF_HEADER_LOGO_WIDTH,"Mian Brothers Petroleum Services",$head);

// set header and footer fonts
$pdf->setHeaderFont(Array("dejavusans", '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language dependent data:
$lg = Array();
$lg['a_meta_charset'] = 'UTF-8';
$lg['a_meta_dir'] = 'rtl';
$lg['a_meta_language'] = 'fa';
$lg['w_page'] = 'page';

// set some language-dependent strings (optional)
$pdf->setLanguageArray($lg);

// ---------------------------------------------------------
// add a page
$pdf->AddPage();


$pdf->Ln();
$pdf->writeHTML('<h3 style="text-align:center"> Customers Report</h3>');
$pdf->Ln(6);
// Restore RTL direction
$pdf->setRTL(true);


// Arabic and English content$pdf->Cell(190,0,"",1);$pdf->Ln(15);
$pdf->SetFont('dejavusans','B',11);
//Create a Customers Table
$pdf->Ln();
$row=' <style> table,tr,th,td{border:1px solid black;border-collapase:collapsed;padding:6px;}  </style>
<table>
<tr>
 <th style="font-weight:bold">گاهک کا نام</th> <th style="font-weight:bold">فون نمبر</th> <th style="font-weight:bold">CNIC</th><th style="font-weight:bold">رقم ادھار</th><th style="font-weight:bold">ایڈوانس رقم</th>
</tr>  ';
$pdf->SetFont('dejavusans','',11);
if($cid==="all"){ 
 foreach($result as $res)
 {
     $name=$res['name'];
     $phoneno=$res['phoneno'];
     $cnic=$res['cnic'];
     $b_amount=$res['b_amount'];
     $a_amount=$res['a_amount'];
     // concatenate a string, instead of calling $pdf->writeHTML()
     $row .= '<tr><td>'.$name.'</td><td>'.$phoneno.'</td> <td>'.$cnic.'</td> <td>'.$b_amount.'</td> <td>'.$a_amount.'</td> </tr>';
 }
}
else{
  $name=$result['name'];
  $phoneno=$result['phoneno'];
  $cnic=$result['cnic'];
  $b_amount=$result['b_amount'];
  $a_amount=$result['a_amount'];
 // concatenate a string, instead of calling $pdf->writeHTML()
 $row .= '<tr><td>'.$name.'</td><td>'.$phoneno.'</td> <td>'.$cnic.'</td><td>'.$b_amount.'</td><td>'.$a_amount.'</td> </tr>';}
$row .= '</table>';
$pdf->writeHTML($row);
 // -------------------Create a Customer Borrow  Table--------------------------------------
 $pdf->writeHTML('<h3 style="text-align:center"> Customer Borrows</h3>');
 $pdf->Ln(6);
 $pdf->SetFont('dejavusans','B',11);
 $row=' <style> table,tr,th,td{border:1px solid black;border-collapase:collapsed;padding:6px;}  </style>
 <table>
 <tr>
  <th style="font-weight:bold">گاهک کا نام</th> <th style="font-weight:bold">مصنوعات کی قسم</th><th style="font-weight:bold">مقدار</th>
  <th style="font-weight:bold">فی اکائی قیمت</th><th style="font-weight:bold">کل قرض کی رقم</th><th style="font-weight:bold">تاریخ</th>
 </tr>  ';
 $pdf->SetFont('dejavusans','',11);
 if($cid==="all"){ 
   foreach($result2 as $res2)
   {
       $id=$res2['cid'];
       $nsql = mysqli_query($conn, "SELECT   * FROM customers where id='$id' "); 
       $nresult=mysqli_fetch_assoc($nsql); $name=$nresult['name'];
       $p_type=$res2['p_type']; $quantity=$res2['quantity']; $pr_lt=$res2['pr_lt'];
       $tamount=$res2['tamount'];   $date=$res2['date'];
       // concatenate a string, instead of calling $pdf->writeHTML()
       $row .= '<tr><td>'.$name.'</td><td>'.$p_type.'</td> <td>'.$quantity.'</td><td>'.$pr_lt.'</td><td>'.$tamount.'</td>  <td>'.$date.'</td>  </tr>';
   }
  }
  else{
   foreach($result2 as $res2)
   {
    $name=$result['name'];
       $p_type=$res2['p_type']; $quantity=$res2['quantity']; $pr_lt=$res2['pr_lt'];
       $tamount=$res2['tamount'];   $date=$res2['date'];
       // concatenate a string, instead of calling $pdf->writeHTML()
       $row .= '<tr><td>'.$name.'</td><td>'.$p_type.'</td> <td>'.$quantity.'</td> <td>'.$pr_lt.'</td> <td>'.$tamount.'</td> <td>'.$date.'</td> </tr>';}
      //  $row .= '<tr><td>'.$name.'</td><td>'.$p_type.'</td><td>'.$quantity.'</td><td>'.$pr_lt.'</td><td>'.$tamount.'</td><td>'.$date.'</td></tr>';}
   }
  $row .= '</table>';
  $pdf->writeHTML($row);

 // -------------------Create a Customer Borrow Payment Table--------------------------------------
 $pdf->writeHTML('<h3 style="text-align:center"> Borrow Payments</h3>');
 $pdf->Ln(6);
 $pdf->SetFont('dejavusans','B',11);
 $row=' <style> table,tr,th,td{border:1px solid black;border-collapase:collapsed;padding:6px;}  </style>
 <table>
 <tr>
  <th style="font-weight:bold">گاهک کا نام</th> <th style="font-weight:bold">ادائیگی کی رقم</th><th style="font-weight:bold">تاریخ</th>
 </tr>  ';
 $pdf->SetFont('dejavusans','',11);
 if(strcmp($cid,'all')){ 
   foreach($result3 as $res3)
   {
       $id=$res3['cid']; 
       $sql4 = mysqli_query($conn, "SELECT   * FROM customers where id='$id' "); 
       $result4=mysqli_fetch_assoc($sql4); $name=$result4['name'];
       $p_amount=$res3['p_amount'];
       $date=$res3['date'];
       // concatenate a string, instead of calling $pdf->writeHTML()
       $row .= '<tr><td>'.$name.'</td><td>'.$p_amount.'</td> <td>'.$date.'</td>  </tr>';
   }
  }
  else{ 
    foreach($result3 as $res3)
    {
      
     $p_amount=$res3['p_amount'];
     $date=$res3['date'];
        // concatenate a string, instead of calling $pdf->writeHTML()
        $row .='<tr><td>'.$name.'</td><td>'.$p_amount.'</td> <td>'.$date.'</td>  </tr>';} }
  $row .= '</table>';
  $pdf->writeHTML($row);
//Close and output PDF document
$pdf->Output('example_01.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+
?>
<style>
table{border:1px solid black}
</style>