<?php // Include the main TCPDF library (search for installation path).
require_once('vendor/TCPDF-main/tcpdf.php');
include "db.php";
session_start();
 $name=$_SESSION['name'];
 if($_GET['date']){
    $cdate=$_GET['date'];
   
 }
 
 $monthNum = $month = date("m",strtotime($cdate));
 $dateObj   = DateTime::createFromFormat('!m', $monthNum);
 $monthName = $dateObj->format('F');
 $report=$_GET['rep'];
 if($report==='monthly'){
    $date='Month: '.$monthName;
}

//Fetch Data from DB
$tamount=0;$tamount2=0;$eamount=0;$pamount=0;$bamount=0;$wamount=0;$cash_pre=0;$tamount3=0;$liters=0;$liters2=0;
if($report==='daily'){
    $date='Date: '.$cdate;
    $prev_date = date('Y-m-d', strtotime('-1 day', strtotime($cdate)));
    $sqln = mysqli_query($conn, "SELECT * FROM cash_hand where date='$prev_date';");
    $resultn=mysqli_fetch_assoc($sqln);
    if($resultn){$cash_pre=$resultn['cash']; }
}
if($report==="daily"){  $sql = mysqli_query($conn, "SELECT   * FROM employee_sale where date='$cdate' and petrol_type='Petrol'"); }
elseif($report==="monthly"){
$sql = mysqli_query($conn, "SELECT   * FROM employee_sale where month(date)=$monthNum and petrol_type='Petrol'");}
$result=mysqli_fetch_all($sql,MYSQLI_ASSOC);
foreach($result as $res){
    $tamount=$tamount+$res['t_amount'];
    $liters=$liters+$res['liters'];
}
if($report==="daily"){  $sql2 = mysqli_query($conn, "SELECT   * FROM employee_sale where date='$cdate' and petrol_type='Diesel'"); }
elseif($report==="monthly"){$sql2 = mysqli_query($conn, "SELECT   * FROM employee_sale where month(date)=$monthNum and petrol_type='Diesel'");}
$result2=mysqli_fetch_all($sql2,MYSQLI_ASSOC);
foreach($result2 as $res2){
    $tamount2=$tamount2+$res2['t_amount'];
    $liters2=$liters2+$res2['liters'];
}
if($report==="daily"){  $sqlz = mysqli_query($conn, "SELECT   * FROM stock_sale where date='$cdate' "); }
elseif($report==="monthly"){$sqlz = mysqli_query($conn, "SELECT   * FROM stock_sale where month(date)=$monthNum ");}
$resultz=mysqli_fetch_all($sqlz,MYSQLI_ASSOC);
foreach($resultz as $resz){
    $tamount3=$tamount3+$resz['tamount'];
}
if($report==="daily"){  $sql3 = mysqli_query($conn, "SELECT   * FROM expenses where  date='$cdate' "); }
elseif($report==="monthly"){$sql3 = mysqli_query($conn, "SELECT   * FROM expenses where month(date)=$monthNum ");}
$result3=mysqli_fetch_all($sql3,MYSQLI_ASSOC);
foreach($result3 as $res3){
    $eamount=$eamount+$res3['amount'];
}
if($report==="daily"){  $sql4 = mysqli_query($conn, "SELECT   * FROM borrow_payment where  date='$cdate' "); }
elseif($report==="monthly"){$sql4 = mysqli_query($conn, "SELECT   * FROM borrow_payment where month(date)=$monthNum ");}
$result4=mysqli_fetch_all($sql4,MYSQLI_ASSOC);
foreach($result4 as $res4){
    $pamount=$pamount+$res4['p_amount'];
}
if($report==="daily"){  $sql5 = mysqli_query($conn, "SELECT   * FROM employee_sale where  date='$cdate' "); }
elseif($report==="monthly"){$sql5 = mysqli_query($conn, "SELECT   * FROM employee_sale where month(date)=$monthNum ");}
$result5=mysqli_fetch_all($sql5,MYSQLI_ASSOC);
foreach($result5 as $res5){
    $bamount=$bamount+$res5['b_amount'];
}
if($report==="daily"){  $sql6 = mysqli_query($conn, "SELECT   * FROM owner_withdraw where  date='$cdate' "); }
elseif($report==="monthly"){$sql6 = mysqli_query($conn, "SELECT   * FROM owner_withdraw where month(date)=$monthNum ");}
$result6=mysqli_fetch_all($sql6,MYSQLI_ASSOC);
foreach($result6 as $res6){
    $wamount=$wamount+$res6['amount'];
}
$teamount=$eamount+$wamount;
$gtotal=$tamount+$tamount2+$tamount3;
$cash=$gtotal-$bamount+$pamount-$teamount;
$tcash=$cash+$cash_pre;

if($report==="daily"){
    $sqlz = mysqli_query($conn, "SELECT * FROM cash_hand where date='$cdate';");
    $resultz=mysqli_fetch_all($sqlz);
    if($resultz){
     
    }
    else{  $insert = mysqli_query($conn,"INSERT INTO `cash_hand`(`cash`, `date`)
        VALUES('$tcash','$cdate')");} }
 
// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($name);
$pdf->SetTitle('Daily Sale Report');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
$head="Generated By: ". $name ."\r\n".$date;
// set default header data
$pdf->SetHeaderData("NO", PDF_HEADER_LOGO_WIDTH,"Mian Bothers Petroleum Service",$head);

// set header and footer fonts
$pdf->setHeaderFont(Array("dejavusans", '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language dependent data:
$lg = Array();
$lg['a_meta_charset'] = 'UTF-8';
$lg['a_meta_dir'] = 'rtl';
$lg['a_meta_language'] = 'fa';
$lg['w_page'] = 'page';

// set some language-dependent strings (optional)
$pdf->setLanguageArray($lg);

// ---------------------------------------------------------

// set font
$pdf->SetFont('dejavusans', '', 12);

// add a page
$pdf->AddPage();

// set LTR direction for english translation
$pdf->setRTL(false);

$pdf->Ln();

// Restore RTL direction
$pdf->setRTL(true);

// set font
$pdf->SetFont('dejavusans', '', 18);

// print newline
$pdf->Ln();

// Arabic and English content$pdf->Cell(190,0,"",1);$pdf->Ln(15);
$pdf->SetFont('dejavusans','',14);
$pdf->Cell(79,0,"کل فروخت",0,0,'C');  $pdf->Cell(25); $pdf->Cell(79,0,"کل اخراجات",0,0,'C');$pdf->Ln(8);
$pdf->SetFont('dejavusans','B',10);

$pdf->Cell(35,10,"پٹرولیم کی قسم",1);
$pdf->Cell(35,10,"لیٹر",1);
$pdf->Cell(35,10,'رقم (Rs)',1);  $pdf->Cell(15);
$pdf->SetFont('dejavusans','',11);
$pdf->Cell(35,10,"کمپنی کا اخراجات",1,0);
$pdf->Cell(35,10,$eamount,1,0);

$pdf->Ln(10); 

$pdf->Cell(35,10,"پیٹرول",1); 
$pdf->Cell(35,10,"$liters",1); 
$pdf->Cell(35,10,$tamount,1); $pdf->Cell(15);

$pdf->Cell(35,10,"مالک کا اخراجات",1,0);
$pdf->Cell(35,10,$wamount,1);$pdf->Ln(10);


$pdf->Cell(35,10,"ڈیزل",1); 
$pdf->Cell(35,10,"$liters2",1); 
$pdf->Cell(35,10,$tamount2,1);$pdf->Cell(15);

$pdf->SetFont('dejavusans','B',11);
 $pdf->Cell(35,10,"کل اخراجات",1,0);
$pdf->Cell(35,10,$eamount,1);
$pdf->Ln(10); $pdf->SetFont('dejavusans', '', 11);

$pdf->Cell(35,10,"دیگر اسٹاک",1); 
$pdf->Cell(35,10,"/-",1); 
$pdf->Cell(35,10,$tamount3,1); 
 $pdf->Ln(10);$pdf->SetFont('dejavusans','B',11);
$pdf->Cell(70,10,"مجموعی طور پر (Rs)",1,0);
$pdf->Cell(35,10,$gtotal,1,0); $pdf->Cell(25);$pdf->Cell(29,10,"کل قرض",0,0,'C');$pdf->Ln(10); 
$pdf->SetFont('dejavusans','',11);
$pdf->Cell(70,10,"نیا ادھار  -",1,0);
$pdf->Cell(35,10,$bamount,1,0); $pdf->Cell(15); $pdf->Cell(40,10,"ادھار کی رقم -",1,0);$pdf->Cell(30,10,$bamount,1,0); $pdf->Ln(10);
$pdf->Cell(70,10,"ادائیگی ادھار   +",1,0);
$pdf->Cell(35,10,$pamount,1,0); $pdf->Cell(15);$pdf->Cell(40,10,"ادائیگی ادھار+",1,0);$pdf->Cell(30,10,$pamount,1,0); 
$pdf->Ln(10);
$pdf->Cell(70,10,"کل اخراجات   -",1,0);
$pdf->Cell(35,10,$eamount,1,0); $pdf->Ln(10);$pdf->SetFont('dejavusans','B',13); 
$pdf->Cell(70,10,"موجود نقدی",1,0);
$pdf->Cell(35,10,$cash,1,0); 
$pdf->Ln(10);
$pdf->Cell(70,10,"پچھلا نقد",1,0);
$pdf->Cell(35,10,$cash_pre,1,0); 
$pdf->Ln(19);
$pdf->Cell(190,10,' موجود نقدی کل: '.$tcash,1,0,'C');
$pdf->Ln();


// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output('example_01.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+
?>